# Pre-processing
## Tokenisation
## Stop words removal
## Lower case conversion (in this project)
## Removing number/digits (in this Project)
## Removing punctuations/special characters (in this project)
## remove characters(foreign language) (in this Project)
## normalisation
## Stemming and Lemmatisation


# Vectorisation
## Bag-of-words (BOW)
## TF-IDF (in this project)
## Word2Vec

In [7]:
import string
import re
import codecs
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import feature_extraction 
from sklearn import linear_model 
from sklearn import pipeline
from sklearn import metrics
from sklearn.model_selection import train_test_split

In [22]:
with open("mtop/en/train.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# Clean or preprocess lines if needed
cleaned_lines = [line.strip() for line in lines]

# Create a DataFrame
eng_df = pd.DataFrame({"English": cleaned_lines})


In [23]:
eng_df.head()

English
0  3232343436343136\tIN:GET_MESSAGE\t4:20:SL:CONT...
1  3132353830343836\tIN:GET_WEATHER\t0:15:SL:LOCA...
2  3136363730313437\tIN:GET_ALARM\t13:17:SL:ORDIN...
3  3232353833343937\tIN:SEND_MESSAGE\t5:12:SL:REC...
4  3133303534343534\tIN:GET_INFO_RECIPES\t6:17:SL...

In [24]:
with open("mtop/de/train.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# Clean or preprocess lines if needed
cleaned_lines = [line.strip() for line in lines]

# Create a DataFrame
de_df = pd.DataFrame({"German": cleaned_lines})
de_df.head()

German
0  3232353834303431\tIN:SEND_MESSAGE\t25:40:SL:GR...
1  3232353833393331\tIN:SEND_MESSAGE\t29:42:SL:RE...
2  3232353833393138\tIN:SEND_MESSAGE\t9:14:SL:REC...
3  3232353833383535\tIN:GET_MESSAGE\t31:39:SL:REC...
4  3232353833373935\tIN:GET_MESSAGE\t21:34:SL:SEN...

In [25]:
with open("mtop/es/train.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# Clean or preprocess lines if needed
cleaned_lines = [line.strip() for line in lines]

# Create a DataFrame
es_df = pd.DataFrame({"Spanish": cleaned_lines})
es_df.head()

Spanish
0  3232353332373537\tIN:CREATE_CALL\t9:21:SL:CONT...
1  3232353332373335\tIN:CREATE_CALL\t9:21:SL:CONT...
2  3232353332363639\tIN:CREATE_CALL\t9:23:SL:CONT...
3  3232353332343532\tIN:CREATE_CALL\t8:25:SL:CONT...
4  3232353332343432\tIN:CREATE_CALL\t9:22:SL:CONT...

In [26]:
with open("mtop/hi/train.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# Clean or preprocess lines if needed
cleaned_lines = [line.strip() for line in lines]

# Create a DataFrame
hi_df = pd.DataFrame({"Hindi": cleaned_lines})
hi_df.head()

Hindi
0  3232353834303437\tIN:SEND_MESSAGE\t0:31:SL:REC...
1  3232353834303234\tIN:GET_MESSAGE\t0:28:SL:DATE...
2  3232353833383038\tIN:SEND_MESSAGE\t39:48:SL:RE...
3  3232353833373335\tIN:SEND_MESSAGE\t16:54:SL:RE...
4  3232353833323935\tIN:GET_MESSAGE\t0:15:SL:RECI...

In [27]:
with open("mtop/th/train.txt", "r", encoding="utf-8") as file:
    lines = file.readlines()

# Clean or preprocess lines if needed
cleaned_lines = [line.strip() for line in lines]

# Create a DataFrame
th_df = pd.DataFrame({"Thai": cleaned_lines})
th_df.head()

Thai
0  3232353834303234\tIN:GET_MESSAGE\t0:48:SL:DATE...
1  3232353834303230\tIN:SEND_MESSAGE\t30:81:SL:CO...
2  3232353834303038\tIN:SEND_MESSAGE\t69:90:SL:GR...
3  3232353833383631\tIN:GET_MESSAGE\t0:42:SL:SEND...
4  3232353833383038\tIN:SEND_MESSAGE\t49:52:SL:RE...

In [31]:
eng_df.head(1)

English
0  3232343436343136\tIN:GET_MESSAGE\t4:20:SL:CONT...

In [32]:
eng_df.iloc[0]

English    3232343436343136\tIN:GET_MESSAGE\t4:20:SL:CONT...
Name: 0, dtype: object

In [34]:
pd.set_option('display.max_colwidth', None)  # Show full column content

# Now, when you display the first row, it should show the entire text
print(eng_df.head())

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             English
0                                      3232343436343136\tIN:GET_MESSAGE\t4:20:SL:CONTACT,21:26:SL:TYPE_CONTENT,36:38:SL:RECIPIENT\tHas Angelika Kratzer video messaged me?\tmessaging\ten_XX\t[IN:GET_MESSAGE [SL:CONTACT Angelika Kratzer ] [SL:TYPE_CONTENT video ] [SL:RECIPIENT me ] ]\t{"tokens":["Has","Angelika","Kratzer","video","messaged","me","?"],"tokenSpans":[{"start":0,"length":3},{"start":4,"length":8},{"start":13,"length":7},{"start":21,"length":5},{"start"

In [36]:
for char in string.punctuation:
    print (char, end=" ")
translate_table = dict((ord(char), None) for char in string.punctuation)

! " # $ % & ' ( ) * + , - . / : ; < = > ? @ [ \ ] ^ _ ` { | } ~ 

In [48]:
data_eng = []
lang_eng = []

In [49]:
for i, line in eng_df.iterrows():
    line = line["English"]
    if len(line) != 0:
        line = line.lower()
        line = re.sub(r"\d+", "", line)
        line = line.translate(translate_table)
        data_eng.append(line)
        lang_eng.append("English")

In [51]:
data_eng

['\tingetmessage\tslcontactsltypecontentslrecipient\thas angelika kratzer video messaged me\tmessaging\tenxx\tingetmessage slcontact angelika kratzer  sltypecontent video  slrecipient me  \ttokenshasangelikakratzervideomessagedmetokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlength',
 '\tingetweather\tsllocationsldatetime\tmaricopa county weather forecast for this week\tweather\tenxx\tingetweather sllocation maricopa county  sldatetime for this week  \ttokensmaricopacountyweatherforecastforthisweektokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlength',
 '\tingetalarm\tslordinal\twhen will my next alarm start\talarm\tenxx\tingetalarm slordinal next  \ttokenswhenwillmynextalarmstarttokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlength',
 '\tinsendmessage\tslrecipientslrecipientslcontentexact\ttext matthew and helen that are you free\tmessaging\tenxx\tinsendmessage slrecipient matthew  slrecipient h

In [53]:
lang_de = []
data_de = []

for i, line in de_df.iterrows():
    line = line["German"]
    if len(line) != 0:
        line = line.lower()
        line = re.sub(r"\d+", "", line)
        line = line.translate(translate_table)
        data_de.append(line)
        lang_de.append("German")

In [54]:
lang_es = []
data_es = []

for i, line in es_df.iterrows():
    line = line["Spanish"]
    if len(line) != 0:
        line = line.lower()
        line = re.sub(r"\d+", "", line)
        line = line.translate(translate_table)
        data_es.append(line)
        lang_es.append("Spanish")

In [57]:
data_es

['\tincreatecall\tslcontact\tllamar a irene powell\tcalling\tesxx\tincreatecall slcontact irene powell  \ttokensllamarairenepowelltokenspansstartlengthstartlengthstartlengthstartlength',
 '\tincreatecall\tslcontact\tllamar a terry murray\tcalling\tesxx\tincreatecall slcontact terry murray  \ttokensllamaraterrymurraytokenspansstartlengthstartlengthstartlengthstartlength',
 '\tincreatecall\tslcontact\tllamar a whitney sutton\tcalling\tesxx\tincreatecall slcontact whitney sutton  \ttokensllamarawhitneysuttontokenspansstartlengthstartlengthstartlengthstartlength',
 '\tincreatecall\tslcontact\tllama a maurice chevalier\tcalling\tesxx\tincreatecall slcontact maurice chevalier  \ttokensllamaamauricechevaliertokenspansstartlengthstartlengthstartlengthstartlength',
 '\tincreatecall\tslcontact\tllamar a regina george\tcalling\tesxx\tincreatecall slcontact regina george  \ttokensllamarareginageorgetokenspansstartlengthstartlengthstartlengthstartlength',
 '\tincreatecall\tslcontact\tllamara a aaro

In [59]:
lang_hi = []
data_hi = []

for i, line in hi_df.iterrows():
    line = line["Hindi"]
    if len(line) != 0:
        line = line.lower()
        line = re.sub(r"\d+", "", line)
        line = re.sub(r"[a-zA-Z]", "", line)
        line = line.translate(translate_table)
        data_hi.append(line)
        lang_hi.append("Hindi")

In [61]:
lang_th = []
data_th = []

for i, line in th_df.iterrows():
    line = line["Thai"]
    if len(line) != 0:
        line = line.lower()
        line = re.sub(r"\d+", "", line)
        line = re.sub(r"[a-zA-Z]", "", line)
        line = line.translate(translate_table)
        data_th.append(line)
        lang_th.append("Thai")

In [63]:
data_th

['\t\t\tตั้งแต่วันอังคาร กลุ่มเพื่อนร่วมงานได้ส่งข้อความหาฉันบ้างไหม\t\t\t  เพื่อน ร่วม งาน   ฉัน   ตั้งแต่ วัน อังคาร  \tตั้งแต่วันอังคารกลุ่มเพื่อนร่วมงานได้ส่งข้อความหาฉันบ้างไหม',
 '\t\t\tส่งข้อความสุขสันต์วันปีใหม่ให้  และ \t\t\t  สุขสันต์ วัน ปี ใหม่        \tส่งข้อความสุขสันต์วันปีใหม่ให้และ',
 '\t\t\tช่วยส่งข้อความไปยังเธรดยูเอฟโอได้ไหม\t\t\t  ยู เอฟ โอ  \tช่วยส่งข้อความไปยังเธรดยูเอฟโอได้ไหม',
 '\t\t\tครอบครัวของฉันส่งอะไรมาให้ฉันบ้างไหม\t\t\t    ของ ฉัน   ครอบครัว     ฉัน  \tครอบครัวของฉันส่งอะไรมาให้ฉันบ้างไหม',
 '\t\t\tช่วยส่งข้อความหา  และ  ได้ไหม\t\t\t       \tช่วยส่งข้อความหาและได้ไหม',
 '\t\t\tส่งข้อความสุขสันต์วันปีใหม่ให้  และ \t\t\t  สุขสันต์ วัน ปี ใหม่        \tส่งข้อความสุขสันต์วันปีใหม่ให้และ',
 '\t\t\tส่งข้อความหาพ่อแม่ของฉัน\t\t\t    ของ ฉัน   พ่อ แม่    \tส่งข้อความหาพ่อแม่ของฉัน',
 '\t\t\tส่งข้อความหาพี่น้องของฉัน\t\t\t    ของ ฉัน   พี่ น้อง    \tส่งข้อความหาพี่น้องของฉัน',
 '\t\t\tฉันต้องการส่งข้อความไปที่แชทของเพื่อนนักถ่ายภาพ\t\t\t  เพื่อน นัก ถ่าย ภาพ  \t

In [64]:
df = pd.DataFrame({"Text": data_eng + data_de + data_es + data_hi + data_th, "Language":lang_eng + lang_de + lang_es + lang_hi + lang_th})

In [65]:
df.head()

Text  \
0                        \tingetmessage\tslcontactsltypecontentslrecipient\thas angelika kratzer video messaged me\tmessaging\tenxx\tingetmessage slcontact angelika kratzer  sltypecontent video  slrecipient me  \ttokenshasangelikakratzervideomessagedmetokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlength   
1                                   \tingetweather\tsllocationsldatetime\tmaricopa county weather forecast for this week\tweather\tenxx\tingetweather sllocation maricopa county  sldatetime for this week  \ttokensmaricopacountyweatherforecastforthisweektokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlength   
2                                                                                                                                      \tingetalarm\tslordinal\twhen will my next alarm start\talarm\tenxx\tingetalarm slordinal next  \ttokenswhenwillmynextalarmstarttokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlength   
3  \tinsendmessage\tslrecipientslrecipientslcontentexact\ttext matthew and helen that are you free\tmessaging\tenxx\tinsendmessage slrecipient matthew  slrecipient helen  slcontentexact are you free  \ttokenstextmatthewandhelenthatareyoufreetokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlengthstartlength   
4                                                                                        \tingetinforecipes\tslrecipesattribute\twhat  ingredients do is have left\trecipes\tenxx\tingetinforecipes slrecipesattribute ingredients  \ttokenswhatingredientsdoishavelefttokenspansstartlengthstartlengthstartlengthstartlengthstartlengthstartlength   

  Language  
0  English  
1  English  
2  English  
3  English  
4  English

In [66]:
df.shape

(62114, 2)

In [67]:
X, y = df.iloc[:,0], df.iloc[:,1]

In [68]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 0)

In [69]:
X_train.shape

(49691,)

In [70]:
X_test.shape

(12423,)

In [71]:
y_train

14830    English
60253       Thai
60702       Thai
10452    English
53195       Thai
          ...   
45891      Hindi
52416       Thai
42613      Hindi
43567      Hindi
2732     English
Name: Language, Length: 49691, dtype: object

# Vectoriser and Model fitting Pipeline

In [73]:
vectorizer = feature_extraction.text.TfidfVectorizer(ngram_range = (1, 3), analyzer = 'char')

In [74]:
pipe_lr_r13 = pipeline.Pipeline([
    ('vectorizer', vectorizer),
    ('clf', linear_model.LogisticRegression())
])


In [75]:
# Model fitting
pipe_lr_r13.fit(X_train, y_train)

Pipeline(steps=[('vectorizer',
                 TfidfVectorizer(analyzer='char', ngram_range=(1, 3))),
                ('clf', LogisticRegression())])

In [76]:
y_predicted = pipe_lr_r13.predict(X_test)

In [77]:
acc = (metrics.accuracy_score(y_test, y_predicted))*100
acc

99.81485953473396

In [80]:
matrix = metrics.confusion_matrix(y_test, y_predicted)
print('confusion matrix : \n', matrix)

confusion matrix : 
 [[3100    2    0    0    0]
 [   8 2680    0    0    0]
 [   0    0 2301    0    0]
 [   9    3    0 2169    0]
 [   0    0    1    0 2150]]


# Model Saving

In [85]:
import pickle

lrFile = open('LRModel.pckl', 'wb')
pickle.dump(pipe_lr_r13, lrFile)
lrFile.close()

# Model Loading


In [86]:
global lrLangDetectModel
lrLangDetectFile = open('LRModel.pckl','rb')
lrLangDetectModel = pickle.load(lrLangDetectFile)
lrLangDetectFile.close()

# Method Definition to call trained Model and make Predictions

In [1]:
def lang_detect(text):
    import string
    import re
    import numpy as np
    import pickle
    translate_table = dict((ord(char), None) for char in string.punctuation)

    global lrLangDetectModel
    lrLangDetectFile = open('LRModel.pckl','rb')
    lrLangDetectModel = pickle.load(lrLangDetectFile)
    lrLangDetectFile.close()

    text = " ".join(text.split())
    text = text.lower()
    text = re.sub(r"\d+","", text)
    text = text.translate(translate_table)
    pred = lrLangDetectModel.predict([text])
    prob = lrLangDetectModel.predict_proba([text])
    return pred[0]
    

In [4]:
text = "What is your name?"
lang_detect(text)

'English'

In [3]:
pip freeze > requirements.txt


Note: you may need to restart the kernel to use updated packages.
